spring.application.name=demo
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.6-flash
spring.ai.google.genai.chat.temperature=0.7

#Gemini Embeddding config
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.text.model=gemini-embedding-001

spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.type=SYNC
spring.ai.mcp.client.toolcallback.enabled=true
spring.ai.mcp.client.streamable-http.connections.email-service.url=http://localhost:8083/mcp

server.error.include-stacktrace=never

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB